### ISSUE TITLE
On selecting the item from items list, items list disappears

### ISSUE THREAD

**Issue by VaibhavP17** [VaibhavP17/ng2-rx-app#4]
What should be the reason for items list to vanish on clicking at any item. The selectedItem works fine but the lists disappears. Can anyone fix that for me ?

**Comment by simpulton** [comment]
You need to return default state in the items reducer if no action type matches

Change 
```
default:
  state;
```
to 
```
default:
  return state;
```

**Comment by VaibhavP17** [comment]
@simpulton Thanks (y)
